# Generated by Django 4.2.3 on 2023-07-12 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=50)),
                ('street_no', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_surgeon', models.BooleanField(default=False)),
                ('is_available_online', models.BooleanField(default=False)),
                ('cnic', models.CharField(max_length=15)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.address')),
                ('gender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.gender')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docsab.role')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.booking')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.user'),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('location_link', models.URLField()),
                ('website_link', models.URLField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.address')),
                ('doctors', models.ManyToManyField(to='docsab.doctor')),
                ('hospital_specialities', models.ManyToManyField(to='docsab.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.speciality'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.doctor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.hospital'),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsab.patient'),
        ),
    ]
