# Generated by Django 4.2.3 on 2023-07-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
