# Generated by Django 4.2.3 on 2023-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0002_patient_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
