# Generated by Django 4.2.3 on 2023-07-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'Specialities'},
        ),
    ]
