# Generated by Django 4.2.3 on 2023-07-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0004_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='docsab.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='total_time',
            field=models.TimeField(),
        ),
    ]
