# Generated by Django 4.2.3 on 2023-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0004_alter_speciality_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
