# Generated by Django 4.2.3 on 2023-07-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0005_booking_time_slot_alter_timeslot_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='total_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
