# Generated by Django 4.2.3 on 2023-07-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0006_remove_timeslot_total_time_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
    ]
