# Generated by Django 4.2.3 on 2023-07-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0007_remove_booking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
