# Generated by Django 4.2.3 on 2023-07-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0008_remove_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docsab.gender'),
        ),
    ]
