# Generated by Django 4.2.3 on 2023-07-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsab', '0009_patient_contact_number_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hospital',
        ),
    ]
